apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
    name: examplePolicy-placementrules
    namespace: example-policy
spec:
    clusterSelector:
        matchExpressions:
            - key: common
              operator: In
              values:
                - "true"
