apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
  annotations:
    ran.openshift.io/ztp-deploy-wave: "100"
status:
  conditions:
  - type: Available
    status: "True"

