apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
  annotations:
    ran.openshift.io/ztp-deploy-wave: "100"
spec:
  channel: $channel
  upstream: $upstream
  desiredUpdate:
    force: false
    version: $version
    image: $image
