apiVersion: policyGenerator/v1
kind: PolicyGenerator
metadata:
  name: clusters-config
  namespace: cluster-config-generator
# The arguments should be given and defined as below with same order --siteConfigPath= --sourcePath= --outPath= --stdout
argsOneLiner: ./testSiteConfig ../source-crs ./out true